openapi: 3.0.1
info:
  title: TestApi
  description: ''
  version: '1.0'
servers:
  - url: https://apim-api-test1.azure-api.net
paths:
  /data:
    get:
      summary: Get Data
      description: get data
      operationId: get-data
      parameters:
        - name: type
          in: query
          description: "Type of data\n"
          required: true
          schema:
            enum:
              - 1
              - 2
              - 3
              - 4
            type: integer
      responses:
        '200':
          description: 'null'
    put:
      summary: Put Data
      description: Put data
      operationId: put-data
      responses:
        '200':
          description: 'null'
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]