on:
  push:
    branches:
      - "!main"
      - "dev"

name: IAC for dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update templates
        run: sh deployment/upload.sh dev
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push app docker container
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: duartefrazao/apim-test-dev:latest
  
  validate-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate templates
        run: |
          az storage blob download --account-name apideployments --container-name templates-dev -n appservice.parameters.json -f deployment/appservice.parameters.json
          az storage blob download --account-name apideployments --container-name templates-dev -n apim.parameters.json -f deployment/apim.parameters.json
          az storage blob download --account-name apideployments --container-name templates-dev -n main.parameters.json -f deployment/main.parameters.json

          az deployment group validate --template-file deployment/apim.json --resource-group api --parameters deployment/apim.parameters.json 
          az deployment group validate --template-file deployment/appservice.json --resource-group api --parameters deployment/appservice.parameters.json 
          az deployment group validate --template-file deployment/main.json --resource-group api --parameters deployment/main.parameters.json 

  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}

    - name: Install dependencies
      run: |
        cd app
        az storage blob download --account-name apideployments --container-name templates-dev -f .env -n .env
        npm install jest
        npm install eslint
    
    - name: Run tests
      run: |
        cd app
        npm run test
    
    - name: Run linter
      run: |
        cd app
        npm run lint
