# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-apim-demo-stripe5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_3ba12cae48304d3fa88450938d68b5b0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e111a78ca02c4534b90f4629455ff9fb }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3ba12cae48304d3fa88450938d68b5b0 }}/duartefrazao/apim-test:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-apim-demo-stripe5'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_42c7a82a253a4cb2877c2d0e1064b0db }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_3ba12cae48304d3fa88450938d68b5b0 }}/duartefrazao/apim-test:${{ github.sha }}'