on:
  push:
    branches:
      - "main"

name: IAC for production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update templates
        run: sh deployment/upload.sh prod
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push app docker container
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: duartefrazao/apim-test:latest
  
  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}

    - name: Install dependencies
      run: |
        cd app
        az storage blob download --account-name apideployments --container-name templates-prod -f .env -n .env
        npm install jest
        npm install eslint
    
    - name: Run tests
      run: |
        cd app
        npm run test
    
    - name: Run linter
      run: |
        cd app
        npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [build,test]
    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run ARM deployment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deployment/main.json
        parameters: storageContainerUrl=${{ secrets.STORAGE_CONTAINER_URL }} storageSAS=${{ secrets.STORAGE_SAS }}
